package com.cabg.enums;

public enum MoleculeRenderMode {
    RECTANGLE_NO_FILL,
    CIRCLE_NO_FILL,
    RECTANGLE_3D_NO_FILL,
    NUMBERS,
    CUSTOM_TEXT,
    RECTANGLE_3D_FILL,
    CIRCLE_FILL,
    SMILEY_FACE,
    MUSIC_NOTE_1,
    MUSIC_NOTE_2,
    HEART,
    CENT_SYMBOL,
    COPYRIGHT_SYMBOL,
    TRADEMARK_SYMBOL,
    INFINITY_SYMBOL,
    KAPPA_SYMBOL,
    SPADE_SYMBOL,
    CLUB_SYMBOL,
    DIAMOND_SYMBOL
}
